---
- name: k8s pre-requisites
  hosts: hypervservers 
  become: yes
  become_user: root
  tasks:

  - name: Turn-off swap
    shell: swapoff -a
  - name: comment out swap settings in the fstab file
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
      replace: '# \1'

  - name: Copy system configurationg file k8s.conf
    copy:
      src: k8s.conf
      dest: /etc/sysctl.d/k8s.conf
  - name: Reload settings from all system configuration files.
    shell: sysctl --system

  - name: get OS release version
    shell: lsb_release -cs
    register: osCodename
    check_mode: no
  - debug:
      msg: "os code name is: {{osCodename.stdout}} {{ansible_distribution_release}}"

  - name: add k8s gpg signing key to repository
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
  - name: adding apt repo
    apt_repository:
            repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
            state: present
            filename: kubernetes.list
  - name: install kubeadm kubectl and kubelet
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet
        - kubeadm
        - kubectl
  - name: restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted
